const en = {
    yourId: "Your id is",
    backToSettings: "Back to App Settings",
    welcome: "Welcome",
    archiveButton: "Archive",
    activeListsButton: "Active Lists",
    menu: "Menu",
    cancel: "Cancel",
    create: "Create",
    confirmation: "Do you want to {action} this list?",
    delete: "Delete",
    archive: "Archive",
    unarchive: "Unarchive",
    leave: "Leave",
    listName: "Enter new list name",
    save: "Save",
    clear: "Clear",
    settings: "Settings",
    filterText: "Hide completed items",
    nameChange: "Change Name",
    list: "List",
    confirmLeave: "Are you sure you want to leave this list?",
    confirmKick: "Are you sure you want to kick this member?",
    kick: "Kick",
    inviteText: "Invite a member with an ID",
    isMember: "User is already a member.",
    userNotExist: "This user doesn't exist.",
    yourself: "You can't invite yourself.",
    invite: "Invite",
    members: "Members",
    newItem: "New Item",
    name: "Name",
    quantity: "Quantity",
    mandatory: "This field is mandatory.",
    add: "Add",
    manageLists: "manage your shopping lists in one place",
    userSelect: "Select User:",
    languageSelect: "Select Language:",
    continueToApp: "Continue into the App",
};

const cz = {
    yourId: "Vaše id je",
    backToSettings: "Zpět na nastavení aplikace",
    welcome: "Vítejte",
    archiveButton: "Archiv",
    activeListsButton: "Aktivní seznamy",
    menu: "Menu",
    cancel: "Zrušit",
    create: "Vytvořit",
    confirmation: "Chcete {action} tento seznam?",
    delete: "Smazat",
    archive: "Archivovat",
    unarchive: "Obnovit",
    leave: "Opustit",
    listName: "Zadejte nový název seznamu",
    save: "Uložit",
    clear: "Vymazat",
    settings: "Nastavení",
    filterText: "Skrýt dokončené položky",
    nameChange: "Změnit název",
    list: "Seznam",
    confirmLeave: "Opravdu chcete opustit tento seznam?",
    confirmKick: "Opravdu chcete vyhodit tohoto člena?",
    kick: "Vyhodit",
    inviteText: "Pozvěte člena pomocí ID",
    isMember: "Uživatel je již členem.",
    userNotExist: "Tento uživatel neexistuje.",
    yourself: "Nemůžete pozvat sami sebe.",
    invite: "Pozvat",
    members: "Členové",
    newItem: "Nová položka",
    name: "Název",
    quantity: "Množství",
    mandatory: "Toto pole je povinné.",
    add: "Přidat",
    manageLists: "spravujte své nákupní seznamy na jednom místě",
    userSelect: "Vyberte uživatele:",
    languageSelect: "Vyberte jazyk:",
    continueToApp: "Pokračovat do aplikace",
};

export const languages = {en, cz}