const en = {
    yourId: "Your id is",
    backToSettings: "Back to App Settings",
    welcome: "Welcome",
    archiveButton: "Archive",
    activeListsButton: "Active Lists",
    menu: "Menu",
    cancel: "Cancel",
    create: "Create",
    confirmation: "Do you want to {action} this list?",
    delete: "Delete",
    archive: "Archive",
    unarchive: "Unarchive",
    leave: "Leave",
    listName: "Enter new list name",
    save: "Save",
    clear: "Clear",
    settings: "Settings",
    filterText: "Hide completed items",
    nameChange: "Change Name",
    list: "List",
};

const cz = {
    yourId: "Vaše id je",
    backToSettings: "Zpět na nastavení aplikace",
    welcome: "Vítejte",
    archiveButton: "Archiv",
    activeListsButton: "Aktivní seznamy",
    menu: "Menu",
    cancel: "Zrušit",
    create: "Vytvořit",
    confirmation: "Chcete {action} tento seznam?",
    delete: "Smazat",
    archive: "Archivovat",
    unarchive: "Obnovit",
    leave: "Opustit",
    listName: "Zadejte nový název seznamu",
    save: "Uložit",
    clear: "Vymazat",
    settings: "Nastavení",
    filterText: "Skrýt dokončené položky",
    nameChange: "Změnit název",
    list: "Seznam",
};

export const languages = {en, cz}